#!/usr/bin/env python3
"""
Regenerates the constant tables hardcoded in vendor/libdv/weighting.c,
vendor/libdv/idct_248.c and vendor/libdv/dct.c, replacing what upstream
libdv computed at runtime via cos()/sin()/sqrt()/pow(). On this project's
m68k Amiga target that runtime computation is a real crash, not just a
slow path: 68040/68060 hardware FPUs implement no transcendental
instructions at all, and executing one traps to the "Line 1111 emulator"
exception (AmigaOS Guru 8000000B) unless fpsp040.library is loaded to
emulate it in software, which a real playback system may not have. Every
table below is a pure function of the DV standard's own constants with no
runtime decoder state, so it is computed once here (offline, in Python,
using this host's own libm) and pasted into the C source as a literal
array - see each C file's own "MintVID adaptation" comment for exactly
where.

This script is not part of the build. It exists so the hardcoded tables
in the vendored C files can be reproduced/audited/regenerated by hand
rather than trusted as opaque numbers - run it and diff the output
against the arrays in the three files above.

Run: python3 tools/gen_dv_tables.py
"""

import math


def c_trunc_to_int32(x):
    """Match C's implicit double -> int32_t assignment: truncate toward zero."""
    return int(math.trunc(x))


def c_rint(x):
    """Match glibc rint()'s default round-to-nearest-even, then the
    (dv_coeff_t) cast in the original code (a no-op narrowing, since
    rint() already returns an integral value)."""
    return int(round(x))


# ---------------------------------------------------------------------
# weighting.c: dv_weight_inverse_88_matrix[64] (dv_coeff_t / int16_t)
#
# Reproduces the original _dv_weight_init()'s W[]/weight_88_inverse_float()
# computation exactly, including its own intermediate double precision.
# ---------------------------------------------------------------------
def gen_weight_inverse_88_matrix():
    def CS(m):
        return math.cos(m * math.pi / 16.0)

    W = [0.0] * 8
    W[0] = 1.0
    W[1] = CS(4) / (4.0 * CS(7) * CS(2))
    W[2] = CS(4) / (2.0 * CS(6))
    W[3] = 1.0 / (2 * CS(5))
    W[4] = 7.0 / 8.0
    W[5] = CS(4) / CS(3)
    W[6] = CS(4) / CS(2)
    W[7] = CS(4) / CS(1)

    temp = [1.0] * 64
    dc = temp[0]
    for y in range(8):
        for x in range(8):
            temp[y * 8 + x] = temp[y * 8 + x] / (W[x] * W[y] / 2.0)
    temp[0] = dc * 4.0

    return [c_rint(temp[i]) for i in range(64)]


# ---------------------------------------------------------------------
# idct_248.c: beta0..beta4 (int32_t, Q30) and dv_idct_248_prescale[64]
# (dv_248_coeff_t / int32_t)
#
# Reproduces the original dv_dct_248_init()'s computation exactly,
# including folding in what used to be _dv_weight_init()'s
# dv_weight_inverse_248_matrix[] (itself built from the same W[] above -
# see weighting.c's own comment for why that intermediate is no longer
# needed at runtime once the final product is precomputed here).
# ---------------------------------------------------------------------
def gen_idct_248_tables():
    def CS(m):
        return math.cos(m * math.pi / 16.0)

    W = [0.0] * 8
    W[0] = 1.0
    W[1] = CS(4) / (4.0 * CS(7) * CS(2))
    W[2] = CS(4) / (2.0 * CS(6))
    W[3] = 1.0 / (2 * CS(5))
    W[4] = 7.0 / 8.0
    W[5] = CS(4) / CS(3)
    W[6] = CS(4) / CS(2)
    W[7] = CS(4) / CS(1)

    dv_weight_inverse_248_matrix = [0.0] * 64
    for z in range(4):
        for x in range(8):
            val = 2.0 / (W[x] * W[2 * z])
            dv_weight_inverse_248_matrix[z * 8 + x] = val
            dv_weight_inverse_248_matrix[(z + 4) * 8 + x] = val
    dv_weight_inverse_248_matrix[0] = 4.0

    dbeta2 = math.cos(math.pi / 4)
    dbeta0 = dbeta2 - 0.5
    dbeta1 = -1 - dbeta0
    dbeta3 = -math.cos(3 * math.pi / 8)
    dbeta4 = math.cos(math.pi / 8)

    beta = {
        "beta0": c_trunc_to_int32(dbeta0 * (2 ** 30)),
        "beta1": c_trunc_to_int32(dbeta1 * (2 ** 30)),
        "beta2": c_trunc_to_int32(dbeta2 * (2 ** 30)),
        "beta3": c_trunc_to_int32(dbeta3 * (2 ** 30)),
        "beta4": c_trunc_to_int32(dbeta4 * (2 ** 30)),
    }

    def C(u):
        return 0.5 / math.sqrt(2.0) if u == 0 else 0.5

    def tickC(u):
        return 1.0 / math.sqrt(2.0) if u == 0 else 0.5

    diag0 = [0.0] * 8
    diag1 = [0.0] * 8
    for k in range(4):
        d = C(k) / (2.0 * math.cos((math.pi * k) / 8.0))
        diag0[k] = d
        diag0[k + 4] = d
    for k in range(8):
        diag1[k] = tickC(k) / (2.0 * math.cos(math.pi * k / 16.0))

    prescale = [0] * 64
    for k in range(8):
        for l in range(8):
            v = 1.0 / diag0[k] * diag1[l] * (2.0 ** 14)
            v = v * dv_weight_inverse_248_matrix[k * 8 + l]
            prescale[k * 8 + l] = c_trunc_to_int32(v)

    return beta, prescale


# ---------------------------------------------------------------------
# dct.c: dv_idct88_basis[8][8] (int32_t, Q14)
#
# KC88[x][y][h][v] = cos(pi*v*(2y+1)/16) * cos(pi*h*(2x+1)/16) is
# separable into COS8[k][n] = cos(pi*k*(2n+1)/16), and folding in the
# per-index C(k) scale factor (0.5/sqrt(2) for k==0, else 0.5) gives the
# single basis matrix A[k][n] = C(k) * COS8[k][n] used both ways
# (KC88[x][y][h][v] = A[v][y]/C(v) * A[h][x]/C(h) restated as
# temp[y*8+x] = sum_v sum_h block[v*8+h] * A[v][y] * A[h][x], which is
# exactly the standard separable 2D IDCT-II form).
# ---------------------------------------------------------------------
def gen_idct88_basis(scale_bits=14):
    def C(k):
        return 0.5 / math.sqrt(2.0) if k == 0 else 0.5

    scale = 1 << scale_bits
    A = [[0] * 8 for _ in range(8)]
    maxabs = 0
    for k in range(8):
        for n in range(8):
            val = C(k) * math.cos(math.pi * k * (2 * n + 1) / 16.0)
            q = round(val * scale)
            A[k][n] = q
            maxabs = max(maxabs, abs(q))
    return A, maxabs


def format_rows(values, per_row=8, indent="\t"):
    lines = []
    for r in range(0, len(values), per_row):
        row = values[r:r + per_row]
        lines.append(indent + ", ".join(str(v) for v in row) + ",")
    return "\n".join(lines)


def main():
    print("=== weighting.c: dv_weight_inverse_88_matrix[64] ===")
    inv88 = gen_weight_inverse_88_matrix()
    print(format_rows(inv88))

    print("\n=== idct_248.c: beta0..beta4, dv_idct_248_prescale[64] ===")
    beta, prescale = gen_idct_248_tables()
    for name in ("beta0", "beta1", "beta2", "beta3", "beta4"):
        print(f"{name} = {beta[name]}")
    print(format_rows(prescale))

    print("\n=== dct.c: dv_idct88_basis[8][8] (Q14) ===")
    A, maxabs = gen_idct88_basis(scale_bits=14)
    print(f"max abs value: {maxabs} ({maxabs.bit_length()} bits)")
    for row in A:
        print("  { " + ", ".join(str(v) for v in row) + " },")


if __name__ == "__main__":
    main()
